spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: 'jdbc:mysql://@database.host@:@database.port@/@database.schema@?serverTimezone=Asia/Seoul'
    username: '@database.username@'
    password: '@database.password@'

server:
  port: 8083
  servlet:
    context-path: /distributemoney
