source ./app_env.sh

echo "SERVICE_NAME_PREFIX="${SERVICE_NAME_PREFIX}
echo "MYSQL_CONTAINER_NAME="${MYSQL_CONTAINER_NAME}
echo "MYSQL_HOST="${MYSQL_HOST}
echo "MYSQL_PORT="${MYSQL_PORT}
echo "MYSQL_USERNAME="${MYSQL_USERNAME}
echo "MYSQL_PASSWORD="${MYSQL_PASSWORD}
echo "MYSQL_SCHEMA="${MYSQL_SCHEMA}
echo "MYSQL_VOLUME_NAME="${MYSQL_VOLUME_NAME}
echo "MYSQL_CONF_VOLUME_NAME="${MYSQL_CONF_VOLUME_NAME}

# mysql 제거
docker rm -f ${MYSQL_CONTAINER_NAME}
docker volume rm ${MYSQL_VOLUME_NAME}
docker volume rm ${MYSQL_CONF_VOLUME_NAME}
